service: nba-stats-app

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    SNS_TOPIC_ARN:
      Ref: FanoutTopic
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: "arn:aws:s3:::daily-nba-game-results/*"
        - Effect: Allow
          Action:
            - sqs:*
            - sns:*
          Resource: "*"
plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

functions:
  saveDailyResultsBDL:
    handler: src/handlers/save_daily_results_bdl.handler
    timeout: 15
    events:
      - schedule:
          rate: cron(0 10 * * ? *)

  saveDailyResultsNbaAPI:
    handler: src/handlers/save_daily_results_nba_api.handler
    timeout: 15
    events:
      - schedule:
          rate: cron(0 10 * * ? *)
custom:
  pythonRequirements:
    dockerizePip: true    # Ensures compatibility with Lambda runtime
    slim: true            # Reduces package size
    strip: false          # Keep debug symbols for better error logs

package:
  exclude:
    - node_modules/**
    - venv/**             # Exclude virtual environment
    - .pytest_cache/**    # Exclude pytest cache
    - tests/**            # Exclude tests
  include:
    - src/**              # Include application source files
    - requirements.txt

resources:
  Resources:
    NBAStatsS3Bucket:    # Logical resource name
      Type: AWS::S3::Bucket
      Properties:
        BucketName: daily-nba-game-results  # S3 bucket name
    # SNS Topic
    FanoutTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: FanoutTopic

    # SQS Queues
    BDLGameQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: BDLGameQueue
    NBAAPIGameQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: NBAAPIGameQueue

    # SQS Subscriptions to SNS
    BDLGameQueueSub:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: FanoutTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt: [ BDLGameQueue, Arn ]
        FilterPolicy:
          source:
            - BallDontLie

    NBAAPIQueueSub:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: FanoutTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt: [ NBAAPIGameQueue, Arn ]
        FilterPolicy:
          source:
            - NBA_API

    # Allow SQS to Receive Messages from SNS
    BDLGameQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: BDLGameQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "sqs:SendMessage"
              Resource:
                Fn::GetAtt: [ BDLGameQueue, Arn ]
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: FanoutTopic

    NBAAPIQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: NBAAPIQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "sqs:SendMessage"
              Resource:
                Fn::GetAtt: [ NBAAPIQueue, Arn ]
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: FanoutTopic