import os
from dotenv import load_dotenv

load_dotenv()

BUCKET_NAME =  os.getenv("BUCKET_NAME")
SNS_TOPIC_ARN = os.getenv("SNS_TOPIC_ARN")
GAME_TABLE_NAME = os.getenv("GAME_TABLE_NAME")
TEAM_TABLE_NAME = os.getenv("TEAM_TABLE_NAME")
PLAYER_TABLE_NAME = os.getenv("PLAYER_TABLE_NAME")
GAME_TABLE_INDEX = os.getenv("GAME_TABLE_INDEX")
TEAM_TABLE_NAME_INDEX = os.getenv("TEAM_TABLE_NAME_INDEX")
TEAM_TABLE_CONFERENCE_INDEX = os.getenv("TEAM_TABLE_CONFERENCE_INDEX")
TEAM_TABLE_DIVISION_INDEX = os.getenv("TEAM_TABLE_DIVISION_INDEX")
PLAYER_TABLE_INDEX = os.getenv("PLAYER_TABLE_INDEX")